apiVersion: v1
kind: Service
metadata:
  name: result-service
  labels:
   name: result-service
   app: demo-voting-app
spec:
 type: NodePort
 ports:
   - port: 5432
     targetPort: 5432   
     nodePort: 30005
 selector:
    name: result-app-pod
    type: demo-voting-app