apiVersion: v1
kind: Service
metadata:
  name: voting-app-service
  labels:
   name: voting-app-service
   app: demo-voting-app
spec:
 type: LoadBalancer
 ports:
   - port: 80
     targetPort: 80 
     nodePort: 30004  
 selector:
    name: voting-app-pod
    type: demo-voting-app
